### DISCUSSION TITLE
Next features or improvements?

### DISCUSSION THREAD

**Discussion by xavierog** [xavierog/moulti#6] [Polls]
As these lines are being written (2024-06-03), Moulti has reached version 1.10.0 and already brings more features than initially envisioned.

**Comment by huyz** [comment]
Man this project is great. I've been thinking about this for years too—like you, especially because I use Ansible.
Thanks for making this. I'll vote once I've used moulti for a bit

**Comment by MartyLake** [comment]
Great project, thanks for creating it!

**Comment by MartyLake** [comment]
Another direction moulti could take, is move to the ad-hoc IDE. For example, instead of receiving logs, moulti could receive steps to execute, and have buttons/shortcuts to

1. re-run
2. watch conditions to trigger the re-run

Example step I would find very useful: `make configure build test`


Another possibility, is to have a one-line terminal at the bottom of moulti, so one can type the next command to run, here that would be either `make build` or `make test` because I know I don’t need to configure everytime.

Another possibility, is to have this one-line terminal support readline, so that "re-run" is effectively "<up> <enter>" when moulti is focused.

**Reply by xavierog** [reply]
As a first reflex, I would check existing tools.

### Existing tools

#### Steps to execute

The first use case you describe reminds me of these tools:

- [procmux](https://github.com/napisani/procmux)
- [mprocs](https://github.com/pvolok/mprocs)
- [mintaka](https://github.com/mwilliamson/mintaka) -- able to focus on the first error
- [mk](https://github.com/orangekame3/mk) -- focused on Makefiles

Have a look, maybe one of those is a closer match to your requirements? I am not sure they "watch conditions to trigger the re-run" though.

#### One-line terminal at the bottom

I had thought of it but did not jump to implementation for various reasons:

- there is a [library to add terminals to Textual applications](https://github.com/mitosch/textual-terminal) (thus providing all your usual comfort: your usual shell, aliases, functions, readline configuration, [fzf](https://github.com/junegunn/fzf) and whatnot) but, if I remember correctly, it is not resize-friendly and that can be a problem
- at the end of the day, this is easily achieved using [tmux](https://github.com/tmux/tmux) (and possibly [tmuxp](https://github.com/tmux-python/tmuxp)):

  ![moulti-tmux](https://github.com/xavierog/moulti/assets/18504173/b0326c15-6f98-4871-bf3c-7343fd9c1aae)

  (possible alternatives: screen, zellij)

### Back to Moulti

Of course, considering Moulti's design (an empty shell that just sits there until an external process fills it with contents), it remains possible to cover your use cases. I invite you to explore the tools above to get a better idea of your ideal setup. If Moulti remains the best candidate, then we can determine:
- what extra core feature would be required to implement your use case
- whether your use case should become a non-core feature (like ansible / diff / manpage), an example or a separate tool.

**Comment by huyz** [comment]
My first request for improvement is to be able to handle Ansible prompts.  Right now I have some playbooks that just freeze up because they prompt the user for a password or to hit enter to continue.

**Reply by xavierog** [reply]
A frontend for Ansible's `vars_prompt` then? I need to study whether Ansible offers a kind of plugin to implement that.

**Reply by xavierog** [reply]
@huyz Moulti v1.13.0 handles Ansible `vars_prompt`.
The ergonomy is not perfect but I believe it is a good start.
Could you please give it a try and let me know whether it does the job?

**Reply by huyz** [reply]
@xavierog Sorry I was too busy to reply right away.

I wasn't thinking of `vars_prompt` actually. I don't use that feature (yet).

For me, I need prompts that are conditional (As I understand it, `vars_prompt` are too inflexible as they're hard to skip based on dynamic conditions.)

I was actually thinking of the `pause`'s `prompt` feature:  https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pause_module.html

Example:

```yaml
- name: Prompt for ssh password if necessary
  when: ansible_password is undefined
  block:
    - name: PAUSE | Conditionally prompt for ssh password
      ansible.builtin.pause:
        prompt: "Password for {{ ansible_user | d('') }}@{{ ansible_host | d('unknown') }}"
        echo: false
      register: password_prompt
      no_log: true

    - name: SET_FACT | Set ansible_password
      ansible.builtin.set_fact:
        ansible_password: "{{ password_prompt.user_input }}"
      no_log: true
```

But huh, I just noticed that even with v1.11.0, I do get prompted for my passphrase when I run a command like `ssh-add`. I didn't know interactivity was already possible!

Let me go ahead and try v1.13.0 and see if your changes make any difference for my `ansible.builtin.pause` case.

You still want me to create an issue?
