### ISSUE TITLE
[FR] Support Ansible's `pause` module's interactive prompting

### ISSUE THREAD

**Issue by huyz** [xavierog/moulti#14]
Following up on the discussion at https://github.com/xavierog/moulti/discussions/6#discussioncomment-10094741 :

I have some Ansible playbooks that won't run properly because of interactive prompts from the builtin Ansible module [pause](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/pause_module.html).

Example:

```yaml
- name: Prompt for ssh password if necessary
  when: ansible_password is undefined
  block:
    - name: PAUSE | Conditionally prompt for ssh password
      ansible.builtin.pause:
        prompt: "Password for {{ ansible_user | d('') }}@{{ ansible_host | d('unknown') }}"
        echo: false
      register: password_prompt
      no_log: true

    - name: SET_FACT | Set ansible_password
      ansible.builtin.set_fact:
        ansible_password: "{{ password_prompt.user_input }}"
      no_log: true
```

The problem I get is:

```
ok: [mac] => {"ansible_facts": {"password_prompt": null}, "changed": false}                                                                                                                                                                                                  
    [WARNING]: Not waiting for response to prompt as stdin is not interactive   
```

This is separate from supporting interactivity for Ansible's `vars_prompt` feature (support for which was [added](https://github.com/xavierog/moulti/discussions/6#discussioncomment-10107117) in v1.13.0)
